[package]
name = "hft-simple-units"
authors = ["Stefan"]
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
readme = "README.md"

[dependencies]
num-traits = "0.2.14"

[dev-dependencies]
# test deps

[build-dependencies]
# no build dependencies
